spring.datasource.url=jdbc:postgresql://localhost:2137/zoo
spring.datasource.username=zoo
spring.datasource.password=zoo
#//spring.cache.type=none
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true